### PR TITLE
Add mail information tooltips

### PR DESCRIPTION
**Pull request by mgreter**
Shows stored mails resources at postal facilities, vehicle usage statistics, storage and sorting percentage.
Shows mail producer info (outgoing and incoming) for residential, commercial and other buildings.

image image image

I assume you automated the translation to other languages!?
May have missed other stuff you deem required (e.g. settings stuff)?

Anyway, leaving it here for consideration.
Thanks for the mod and best regards!

### CODE REVIEW

**Comment by 89pleasure** [comment]
Thank you for your contribution on ET. Currently I'm quite busy (started a new job). But what I see first is, that the UI part is missing. Tooltips should always be able to deactivate. Especially if they are added to buildings which have a lot of info (like mixed zone buildings). 

I would see your additions as details. So you could combine the setting to a "Mail details" or something similar to "household details" settings under zones.

**Comment by mgreter** [comment]
image

image image

image image

image

**Comment by 89pleasure** [comment]
Thanks for the addition to the UI. 
But I saw you removed the ExtendedLayout setting from some of the tooltip builders. This is not in scope of the merge request and should be an extra task so we can split those two topics which has nothing to do with each other. I would like to discuss it before.

**Comment by mgreter** [comment]
Feel free to only cherry pick the commits you like ;)

**Comment by 89pleasure** [comment]
Sorry @mgreter , was really busy with FindStuff. I will look into this next. :)

**Pull request closed without merging**
